steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true","appengine:deploy"]
  #  - name: gcr.io/cloud-builders/docker
  #    args: ["build", "-t", "gcr.io/$PROJECT_ID/k8s-springboot-data-rest", "--build-arg=JAR_FILE=target/po-rest-service-1.0.jar", "."]
  #images: ["gcr.io/$PROJECT_ID/k8s-springboot-data-rest"]