env: flex
runtime: java
runtime_config:
  jdk: openjdk8

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3

handlers:
  - url: /.*
    script: this field is required, but ignored